spring.application.name=Spring-training

# Ch?t profile mu?n ch?y ? ?ây (dev ho?c prod)
spring.profiles.active=dev

# Các c?u hình chung cho c? 2 môi tr??ng
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true