server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_management_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 0801
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect