server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_management_db?createDatabaseIfNotExist=true
    username: root
    password: kiendz29
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update