server.port=8080
app.environment=DEVELOPMENT
app.message=Chao mung ban den voi moi truong DEV


spring.datasource.url=jdbc:mysql://localhost:3306/order_management?useSSL=false&serverTimezone=Asia/Bangkok
spring.datasource.username=root
spring.datasource.password=27062004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Chu?i bí m?t ?? ký JWT (ít nh?t 32 ký t?)
jwt.signerKey=zxcvbnm1234567890asdfghjklqwertyuiop1234567890