spring.application.name=Spring-training
server.port=8081

# Thông tin chung ?? b?n dùng trong AppConfig (n?u c?n)
loda.mysql.url=jdbc:mysql://localhost:3306/thenn?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
loda.mysql.username=root
loda.mysql.password=27062004

# C?u hình chính cho Spring Boot Starter Data JPA
spring.datasource.url=jdbc:mysql://localhost:3306/thenn?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=27062004

# Hibernate & JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect