server.port=8080
logging.level.root=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/order_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Bangkok
spring.datasource.username=kiennt
spring.datasource.password=123132

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true