spring.application.name=order-management
spring.profiles.active=dev
# Show SQL queries (Hibernate/JPA)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE